// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiqIyvsdjpkXFIEM5siSmPtH-flOrRVIA',
    appId: '1:382260523481:web:3c47406dfe6e0a5eb6a9c8',
    messagingSenderId: '382260523481',
    projectId: 'flutter-note-b84ef',
    authDomain: 'flutter-note-b84ef.firebaseapp.com',
    storageBucket: 'flutter-note-b84ef.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJyBT-ZdDRKNaPCbzwDRJdKDIxjqtzS4A',
    appId: '1:382260523481:android:79818866a43ded5fb6a9c8',
    messagingSenderId: '382260523481',
    projectId: 'flutter-note-b84ef',
    storageBucket: 'flutter-note-b84ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgvzXYIleia97dq4RG7VSmK2CP4RKn62Y',
    appId: '1:382260523481:ios:33638188b7e122fab6a9c8',
    messagingSenderId: '382260523481',
    projectId: 'flutter-note-b84ef',
    storageBucket: 'flutter-note-b84ef.appspot.com',
    iosClientId: '382260523481-bvepuos1c1d6l438q5o2vnnkdou8dag1.apps.googleusercontent.com',
    iosBundleId: 'com.example.note',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgvzXYIleia97dq4RG7VSmK2CP4RKn62Y',
    appId: '1:382260523481:ios:33638188b7e122fab6a9c8',
    messagingSenderId: '382260523481',
    projectId: 'flutter-note-b84ef',
    storageBucket: 'flutter-note-b84ef.appspot.com',
    iosClientId: '382260523481-bvepuos1c1d6l438q5o2vnnkdou8dag1.apps.googleusercontent.com',
    iosBundleId: 'com.example.note',
  );
}
